In [1]:
import numpy as  np

In [2]:
# Create Numpy Array

# Default List
my_list = [1,2,3]

# Create Numpy Array
x = np.array(my_list)
type(x)

numpy.ndarray

In [3]:
# Create Numpy Matrix
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Identity Matrix
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [9]:
# Random Integer (low, high exclusive, number of results)
print(np.random.randint(1,100, 5))

# Sample from Standard Normal Distribution
print(np.random.randn(5))

[ 1 46 91 19 63]
[-1.3055475   0.16122165 -1.6950701   0.3968678  -1.67269927]
